### ISSUE TITLE
git extension not able to locate repo

### ISSUE THREAD

**Issue by jgotty777** [halcyon-tech/git-client-ibmi#3]
I have a repo on the ibm i and installed both Code for IBMi and the corresponding git integration extension. After setting my home location to the location of the repo, I receive the error "/home/<git location here>/ is not a git repo"

**Comment by worksofliam** [comment]
@jgotty777 Where is that git installed from? We generally only support the version that is installed from yum (`/QOpenSys/pkgs/bin/git`).
